---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: home
  label: 首页
  create: documents
  match: "**/*"
  templates:
  - info-page
- type: heading
  label: 花雨满天
- type: directory
  path: body
  label: 身
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: mind
  label: 心
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: spirit
  label: 灵
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Content
- type: directory
  path: content/blog-posts
  label: Blog Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: document
  path: content/data/authors.json
  label: Author List
- type: document
  path: content/data/info.json
  label: Info Page
- type: heading
  label: Config
- type: document
  path: content/data/config.json
  label: Site Info
upload_dir: static
public_path: https://vd2.bdstatic.com/mda-mfgcwtf01gavzhcc/fhd/cae_h264_nowatermark/1623921070451806900/mda-mfgcwtf01gavzhcc.mp4?v_from_s=nj_haokan_4469&auth_key=1623993280-0-0-e3398bcf62aceece23cfda8721f40270&bcevod_channel=searchbox_feed&pd=1&pt=3&abtest=
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
